### ISSUE TITLE
Service is crashing: EPIPE error

### ISSUE THREAD

**Issue by joeyguerra** [joeyguerra/devchitchat#14]
The service crashes. I finally got it to log an error message, it was:

error Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

After some research on the web, I decided to just add an error handler on every socket.io socket that just logs the error then does nothing after that, thinking that the error will just get swallowed.

**Comment by ijoey** [comment]
This is still happening. I installed IO.js in prod because the net.js code is different than the Node version to see if that would provide additional information or maybe even "fix" this issue.

**Comment by joeyguerra** [comment]
I don't see it happening anymore. Gonna close this for now.
