### ISSUE TITLE
Quote past messages in a conversation

### ISSUE THREAD

**Issue by gizach** [joeyguerra/devchitchat#20]
I want to quote other users messages in devchitchat so that it is clearer when my own message is in reply to another person's message.

The user's avatar should be shown so it's clear who I am quoting.

**Comment by ijoey** [comment]
Can you please write the scenario in Gherkin?

**Comment by kijanawoodard** [comment]
http://howfuckedismydatabase.com/nosql/

**Comment by ijoey** [comment]
Ok. So I know it may have sounded like that, but I was serious.

**Comment by zach-binary** [comment]
GIVEN I'm in devchitchat
WHEN I double click on a previous message in chat
THEN In the preview I should see the message I clicked, along with the users avatar inside of a blockquote, appended to where my cursor was at when I double clicked the message

GIVEN I'm in devchitchat
WHEN I double click on a message by Kijana
THEN In the textbar I should see "[quote from Kijana]" appended to where my cursor was at when I double clicked the message.

8-D
