### ISSUE TITLE
Radio station

### ISSUE THREAD

**Issue by joeyguerra** [joeyguerra/devchitchat#25]
Given that I'm on devchitchat
When I want to listen to a song
And I enter "pipbot radio"
Then everyone in the chat room hears the same music.

**Comment by kijanawoodard** [comment]
Does everyone hear it, or just you?

-----Original Message-----

**Comment by ijoey** [comment]
everyone.

**Comment by mkerfeld** [comment]
Can I specify the song?

**Comment by ijoey** [comment]
Yes, but that's a different story.
