### ISSUE TITLE
inproc and remote bus APIs don't match.

### ISSUE THREAD

**Issue by joeyguerra** [joeyguerra/devchitchat#26]
I want to refactor the inprocbus to have the same API and design as the "remote" bus module so I can use them interchangeably, thusly enabling the ability to deploy the app in distinct components.

**Comment by kijanawoodard** [comment]
Just make sure that the caller's expectations are the same in both cases. Code that expects local semantics get ensnared in the fallacies of distributed computing.

-----Original Message-----

**Comment by ijoey** [comment]
Then perhaps this is a matter of asking the wrong question. My initial thought was to implement a code design that can be deployed with multiple "processors" should I want to scale and that it would be "easy" to design the code for that.
